version: '3.8'

services:
  qlik-cloud-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: qlik-cloud-mcp:latest
    container_name: qlik-cloud-mcp
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - NODE_ENV=production
    networks:
      - qlik-cloud-network

networks:
  qlik-cloud-network:
    driver: bridge
